#!/usr/bin/env python3
"""
Generate `docs/development/phase-1-test-matrix.xlsx`.

The plain-text companion lives at
`docs/development/phase-1-e2e-runbook.md` (kept lowercase so it
escapes the repo-wide `PHASE_*.md` gitignore pattern that
covers in-flight work notes).

Run with:

    pipx run --spec openpyxl python3 scripts/generate_phase1_test_matrix.py

Or with a local venv that has openpyxl installed.

The workbook is the canonical artefact reviewers paste into the
QA tracker (Linear, Notion, Jira). Each sheet is a self-contained
scenario set. Status columns start blank so the operator fills
them in as they validate the build.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

try:
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill, Border, Side
    from openpyxl.utils import get_column_letter
    from openpyxl.worksheet.table import Table, TableStyleInfo
except ModuleNotFoundError as e:
    print(f"openpyxl not installed: {e}", file=sys.stderr)
    print("install with: pipx install openpyxl  OR  pip install openpyxl", file=sys.stderr)
    sys.exit(2)


REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "docs" / "development" / "phase-1-test-matrix.xlsx"

# ── styles ────────────────────────────────────────────────────────────────────

HEADER_FILL = PatternFill("solid", fgColor="1F2937")
HEADER_FONT = Font(name="Calibri", size=11, bold=True, color="F9FAFB")
TITLE_FONT = Font(name="Calibri", size=14, bold=True, color="111827")
SUBTLE_FONT = Font(name="Calibri", size=10, italic=True, color="6B7280")
BODY_FONT = Font(name="Calibri", size=10)
BORDER = Border(
    left=Side(style="thin", color="D1D5DB"),
    right=Side(style="thin", color="D1D5DB"),
    top=Side(style="thin", color="D1D5DB"),
    bottom=Side(style="thin", color="D1D5DB"),
)
WRAP = Alignment(wrap_text=True, vertical="top", horizontal="left")
HEADER_ALIGN = Alignment(wrap_text=True, vertical="center", horizontal="left")

# Severity / priority palette
PALETTE = {
    "P0":   PatternFill("solid", fgColor="DC2626"),  # red
    "P1":   PatternFill("solid", fgColor="EA580C"),  # orange
    "P2":   PatternFill("solid", fgColor="CA8A04"),  # yellow
    "P3":   PatternFill("solid", fgColor="0891B2"),  # cyan
    "PASS": PatternFill("solid", fgColor="16A34A"),  # green
    "FAIL": PatternFill("solid", fgColor="DC2626"),
    "BLOCKED": PatternFill("solid", fgColor="6B7280"),
}


def write_table(ws, headers: list[str], rows: list[list], table_name: str, start_row: int = 1):
    """Write a styled table starting at start_row."""
    for j, h in enumerate(headers, start=1):
        c = ws.cell(row=start_row, column=j, value=h)
        c.fill = HEADER_FILL
        c.font = HEADER_FONT
        c.alignment = HEADER_ALIGN
        c.border = BORDER

    for i, row in enumerate(rows, start=start_row + 1):
        for j, value in enumerate(row, start=1):
            c = ws.cell(row=i, column=j, value=value)
            c.font = BODY_FONT
            c.alignment = WRAP
            c.border = BORDER
            if isinstance(value, str) and value in PALETTE:
                c.fill = PALETTE[value]
                if value in ("P0", "P1", "FAIL"):
                    c.font = Font(name="Calibri", size=10, bold=True, color="F9FAFB")

    end_row = start_row + len(rows)
    end_col = get_column_letter(len(headers))
    ref = f"A{start_row}:{end_col}{end_row}"
    tbl = Table(displayName=table_name, ref=ref)
    tbl.tableStyleInfo = TableStyleInfo(
        name="TableStyleMedium2", showRowStripes=True
    )
    ws.add_table(tbl)
    ws.freeze_panes = ws.cell(row=start_row + 1, column=1)


def autosize(ws, widths: list[int]):
    for j, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(j)].width = w


def add_title_block(ws, title: str, subtitle: str = ""):
    ws.cell(row=1, column=1, value=title).font = TITLE_FONT
    if subtitle:
        ws.cell(row=2, column=1, value=subtitle).font = SUBTLE_FONT
    ws.row_dimensions[1].height = 22


# ── sheets ────────────────────────────────────────────────────────────────────

def sheet_summary(ws):
    add_title_block(
        ws,
        "Halcón — Phase 1 E2E Test Matrix",
        "Branch: phase-1/security-cleanup-ci · Generated by scripts/generate_phase1_test_matrix.py",
    )
    headers = [
        "Area",
        "Phase 1 Deliverable",
        "Commit",
        "Sheet",
        "Total Tests",
        "Automated",
        "Manual / E2E",
        "Required for merge?",
    ]
    rows = [
        ["P1-A", "CI: Paloma deploy-key wiring + composite action + runbook",
         "cccfda7", "P1-A_CI", 5, 4, 1, "Yes"],
        ["P1-B", "SSRF guard for http_request / web_fetch / http_probe",
         "4e5fd9c", "P1-B_SSRF", 18, 17, 1, "Yes"],
        ["P1-B", "OAuth state validation (constant-time across 3 flows)",
         "240e6d2", "P1-B_OAuth", 8, 5, 3, "Yes"],
        ["P1-B", "Upstream-error body truncation + token redaction",
         "d8c3370", "P1-B_LogSanit", 8, 6, 2, "Yes"],
        ["P1-C", "Zombie scaffolding removed (role_policy, failure_cascade, scheduling)",
         "d0c7919", "P1-C_Cleanup", 4, 3, 1, "Yes"],
        ["P1-C", "Obsolete root-level docs deleted",
         "e3254f9", "P1-C_Cleanup", 2, 2, 0, "Yes"],
        ["P1-D", "Coverage informational job + CONTRIBUTING / SECURITY accuracy",
         "94d6d08", "P1-D_Standards", 6, 4, 2, "Yes"],
        ["P1-E", "NetworkPolicyDenied variant + CLI sink rendering",
         "043740d", "P1-E_Observability", 4, 3, 1, "Yes"],
        ["—", "Build & install on operator machine",
         "(local)", "Smoke", 6, 0, 6, "Yes"],
        ["—", "Cross-cutting regression sweep",
         "(local)", "Regression", 7, 6, 1, "Yes"],
    ]
    write_table(ws, headers, rows, "Summary", start_row=4)
    autosize(ws, [10, 60, 14, 18, 12, 12, 14, 18])


def sheet_p1a_ci(ws):
    add_title_block(
        ws,
        "P1-A · CI plumbing for cuervo-ai/paloma",
        "Verifies the composite action behaves correctly with and without the secret.",
    )
    headers = ["#", "Scenario", "Steps", "Expected result", "Severity",
               "Type", "Status", "Notes"]
    rows = [
        [1,
         "Composite action file syntax is valid",
         "1) yamllint .github/actions/setup-private-deps/action.yml\n"
         "2) gh workflow view CI --repo cuervo-ai/halcon (after push)",
         "yamllint exits 0; gh shows the action wired in clippy/check/test-linux/test-macos.",
         "P1", "Auto", "", ""],
        [2,
         "Workflow fails loud when PALOMA_HTTPS_TOKEN is missing",
         "Push branch to origin without setting the secret. Inspect Clippy job logs.",
         "Step 'Verify token present' fails with ::error 'Secret PALOMA_HTTPS_TOKEN is not set' "
         "and a pointer to docs/development/CI_SECRETS.md. Subsequent steps are skipped.",
         "P0", "E2E", "", "User-visible runbook value"],
        [3,
         "Workflow succeeds when PALOMA_HTTPS_TOKEN is configured",
         "Set secret via: gh secret set PALOMA_HTTPS_TOKEN --repo cuervo-ai/halcon\n"
         "Re-run the failing workflow.",
         "Clippy + Check + Test-Linux jobs all turn green; cargo successfully fetches "
         "cuervo-ai/paloma at tag v0.1.0.",
         "P0", "E2E", "", "Bridge to Phase 2"],
        [4,
         "Local cargo build still works without the env var",
         "cd ~/Documents/Projects/cuervo-ai/active/halcon && \n"
         "cargo check --workspace --no-default-features --features tui --exclude momoto-* ",
         "cargo check passes locally because dev's git auth (SSH key / gh CLI) "
         "resolves cuervo-ai/paloma transparently.",
         "P1", "Auto", "", ""],
        [5,
         ".cargo/config.toml has git-fetch-with-cli = true",
         "grep 'git-fetch-with-cli' .cargo/config.toml",
         "Returns the line. Without it, libgit2 ignores the global git config rewrite "
         "and CI authentication never takes effect.",
         "P1", "Auto", "", ""],
    ]
    write_table(ws, headers, rows, "P1A_CI", start_row=4)
    autosize(ws, [4, 38, 60, 60, 10, 8, 10, 30])


def sheet_p1b_ssrf(ws):
    add_title_block(
        ws,
        "P1-B · SSRF guard (network policy)",
        "Each row is an URL that must be REJECTED before the request leaves the agent.",
    )
    headers = ["#", "URL / target", "Tool", "Expected category", "Reject reason",
               "Severity", "Type", "Status", "Notes"]
    rows = [
        [1, "http://127.0.0.1/admin", "http_request", "Loopback v4",
         "loopback (127.0.0.0/8)", "P0", "Auto", "", "covered by unit test loopback_v4_rejected"],
        [2, "http://[::1]/", "http_request", "Loopback v6",
         "loopback (::1)", "P0", "Auto", "", ""],
        [3, "http://[::ffff:127.0.0.1]/", "http_request", "IPv4-mapped loopback",
         "loopback (127.0.0.0/8)", "P0", "Auto", "", "regression test for to_ipv4_mapped"],
        [4, "http://10.0.0.1/", "web_fetch", "RFC1918 10/8",
         "private (RFC1918)", "P0", "Auto", "", ""],
        [5, "http://172.16.0.1/", "web_fetch", "RFC1918 172.16/12",
         "private (RFC1918)", "P0", "Auto", "", ""],
        [6, "http://192.168.1.1/", "web_fetch", "RFC1918 192.168/16",
         "private (RFC1918)", "P0", "Auto", "", ""],
        [7, "http://169.254.169.254/latest/meta-data/", "http_request", "AWS IMDS",
         "blocked hostname OR link-local (169.254/16)", "P0", "Auto", "", "Critical for cloud-deployed Halcón"],
        [8, "http://metadata.google.internal/", "http_request", "GCP IMDS",
         "blocked hostname", "P0", "Auto", "", ""],
        [9, "http://metadata.azure.com/", "web_fetch", "Azure IMDS",
         "blocked hostname", "P0", "Auto", "", ""],
        [10, "http://[fe80::1]/", "http_request", "IPv6 link-local",
         "link-local (fe80::/10)", "P0", "Auto", "", ""],
        [11, "http://[fc00::1]/", "http_request", "IPv6 unique-local",
         "unique-local (fc00::/7)", "P0", "Auto", "", ""],
        [12, "http://100.64.0.1/", "http_request", "CGNAT",
         "CGNAT (100.64.0.0/10)", "P1", "Auto", "", "RFC6598"],
        [13, "http://0.0.0.0/", "http_request", "Unspecified v4",
         "unspecified (0.0.0.0)", "P1", "Auto", "", ""],
        [14, "ftp://example.com/", "http_request", "Bad scheme",
         "scheme rejected (use http/https)", "P1", "Auto", "", ""],
        [15, "javascript:alert(1)", "http_request", "Bad scheme",
         "scheme rejected", "P1", "Auto", "", ""],
        [16, "not-a-url", "http_request", "Malformed URL",
         "InvalidUrl", "P1", "Auto", "", ""],
        [17, "http://example.com/", "http_request", "Public domain (allow)",
         "Reaches network (or 4xx from server) — guard does NOT block.",
         "P1", "Auto", "", "Negative test: must allow legitimate use"],
        [18, "Real binary: halcon agent prompted to GET 127.0.0.1",
         "halcon (interactive)", "End-to-end",
         "Tool returns is_error=true with metadata.blocked_by=network_policy. "
         "Agent reports the block to the user; no socket connect occurs.",
         "P0", "E2E", "", "Operator validates after install"],
    ]
    write_table(ws, headers, rows, "P1B_SSRF", start_row=4)
    autosize(ws, [4, 45, 14, 22, 38, 10, 8, 10, 28])


def sheet_p1b_oauth(ws):
    add_title_block(
        ws,
        "P1-B · OAuth state validation (constant-time)",
        "Three OAuth flows: halcon-auth (API), halcon-cli/sso (Cenzontle), halcon-mcp.",
    )
    headers = ["#", "Flow", "Scenario", "Input", "Expected result",
               "Severity", "Type", "Status", "Notes"]
    rows = [
        [1, "halcon-auth::OAuthFlow",
         "Matching states succeed",
         "expected_state='abc' received_state='abc'",
         "exchange_code returns Ok with the access token. Test: exchange_code_success.",
         "P0", "Auto", "", ""],
        [2, "halcon-auth::OAuthFlow",
         "Mismatch rejected",
         "expected_state='abc' received_state='xyz'",
         "Returns AuthFailed('OAuth state mismatch …'). No HTTP request issued.",
         "P0", "Auto", "", "exchange_code_rejects_state_mismatch"],
        [3, "halcon-auth::OAuthFlow",
         "Empty expected_state rejected",
         "expected_state='' received_state=''",
         "Returns AuthFailed('expected_state is empty …'). Prevents accidental disablement.",
         "P0", "Auto", "", "exchange_code_rejects_empty_expected_state"],
        [4, "halcon-cli::sso (Cenzontle)",
         "ct_eq used in callback handler",
         "grep 'ct_eq' crates/halcon-cli/src/commands/sso.rs",
         "Match found at exactly one site; `received_state != expected_state` removed.",
         "P0", "Auto", "", "Ensures regression detection"],
        [5, "halcon-mcp::oauth",
         "ct_eq used in receive_auth_code",
         "grep 'ct_eq' crates/halcon-mcp/src/oauth.rs",
         "Match found in the loopback callback handler.",
         "P0", "Auto", "", ""],
        [6, "halcon-cli::sso (Cenzontle) — E2E",
         "End-to-end login with browser tampering",
         "1) Run `halcon auth login cenzontle`.\n"
         "2) Edit the redirect URL in the browser to change the `state` param.\n"
         "3) Submit the modified URL.",
         "CLI prints 'State mismatch in OAuth callback (CSRF protection triggered).' "
         "and exits with non-zero.",
         "P1", "E2E", "", "Hard to automate; valuable manual run"],
        [7, "halcon-cli::sso — happy path",
         "End-to-end login flow",
         "halcon auth login cenzontle (let it complete normally)",
         "Browser opens, callback received, token written to keystore, "
         "show_available_models prints the model list.",
         "P1", "E2E", "", ""],
        [8, "subtle dependency",
         "subtle = '2' declared in 3 Cargo.toml files",
         "grep 'subtle' crates/halcon-auth/Cargo.toml crates/halcon-cli/Cargo.toml "
         "crates/halcon-mcp/Cargo.toml",
         "All three return a hit at the dependency line.",
         "P1", "Auto", "", ""],
    ]
    write_table(ws, headers, rows, "P1B_OAuth", start_row=4)
    autosize(ws, [4, 30, 32, 50, 60, 10, 8, 10, 25])


def sheet_p1b_logsanit(ws):
    add_title_block(
        ws,
        "P1-B · Upstream error-body sanitization",
        "Validates that propagated HalconError::ApiError messages never carry tokens.",
    )
    headers = ["#", "Input body", "Expected output substring(s)",
               "Forbidden substring(s)", "Severity", "Type", "Status", "Notes"]
    rows = [
        [1, '{"error":"forwarded sk-ant-api01-AAA-bbb-XYZ rejected"}',
         "[REDACTED]", "sk-ant-api01-AAA-bbb-XYZ",
         "P0", "Auto", "", "sanitize_error_body_redacts_anthropic_key"],
        [2, "Authorization: Bearer abcdef.GhIjKl.123456",
         "[REDACTED]", "abcdef.GhIjKl.123456",
         "P0", "Auto", "", "redacts_bearer_token"],
        [3, "stale eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.signaturepart token",
         "[REDACTED]", "eyJhbGciOiJIUzI1NiJ9",
         "P0", "Auto", "", "redacts_jwt"],
        [4, '{"error":"AIza1234567890abcdefghijklmnopqrstuv"}',
         "[REDACTED]", "AIza1234567890abcdef",
         "P0", "Auto", "", ""],
        [5, '{"error":"sk-proj-01234567890abcdef refused"}',
         "[REDACTED]", "sk-proj-01234567890abcdef",
         "P0", "Auto", "", ""],
        [6, "Body of length 2048 bytes (e.g. \"x\".repeat(2048))",
         "[truncated 1536 bytes]", "(none)",
         "P1", "Auto", "", "truncates at 512 bytes; UTF-8 char-boundary safe"],
        [7, "plain server error: internal",
         "plain server error: internal", "[REDACTED]",
         "P2", "Auto", "", "negative — short body must be unchanged"],
        [8, "Error returned by Cenzontle in real CLI session",
         "User sees a friendly truncated error",
         "Any 32+ char base64 string after Bearer/sk-/eyJ",
         "P1", "E2E", "", "Operator: cause an upstream 500 to validate"],
    ]
    write_table(ws, headers, rows, "P1B_LogSanit", start_row=4)
    autosize(ws, [4, 60, 35, 35, 10, 8, 10, 35])


def sheet_p1c_cleanup(ws):
    add_title_block(
        ws,
        "P1-C · Zombie cleanup verification",
        "Removed scaffolding and obsolete docs must not leave dangling references.",
    )
    headers = ["#", "Removed item", "Verification command", "Expected",
               "Severity", "Type", "Status", "Notes"]
    rows = [
        [1, "crates/halcon-runtime/src/executor/role_policy.rs",
         "grep -rn 'role_policy\\|RolePolicy' crates/ --include='*.rs'",
         "Zero hits.",
         "P1", "Auto", "", ""],
        [2, "crates/halcon-runtime/src/executor/failure_cascade.rs",
         "grep -rn 'pub mod failure_cascade' crates/halcon-runtime/src/",
         "Zero hits. (orchestrator's `failure_cascade_*` test names are LOCAL test names — "
         "not imports of the deleted module — and intentionally remain.)",
         "P1", "Auto", "", ""],
        [3, "crates/halcon-runtime/src/executor/scheduling.rs",
         "grep -rn 'WaveBudgetPolicy\\|executor::scheduling' crates/ --include='*.rs'",
         "Zero hits.",
         "P1", "Auto", "", ""],
        [4, "Workspace still compiles after removal",
         "cargo check --workspace --no-default-features --features tui --exclude momoto-*",
         "Exit 0; only pre-existing warnings.",
         "P0", "Auto", "", ""],
        [5, "Five obsolete docs deleted from docs/ root",
         "ls docs/STREAMING_*.md docs/SSE_*.md docs/REMOTE_CONTROL_V2_ARCHITECTURE.md "
         "docs/SYSTEM_MATURATION_PHASE1.md 2>&1",
         "All entries report 'No such file or directory'.",
         "P2", "Auto", "", ""],
        [6, "No README / CHANGELOG references the deleted docs",
         "grep -rn 'STREAMING_BACKEND_GUIDE\\|REMOTE_CONTROL_V2_ARCHITECTURE\\|SYSTEM_MATURATION_PHASE1' "
         ". --include='*.md'",
         "Zero hits.",
         "P2", "Auto", "", ""],
    ]
    write_table(ws, headers, rows, "P1C_Cleanup", start_row=4)
    autosize(ws, [4, 50, 80, 60, 10, 8, 10, 25])


def sheet_p1d_standards(ws):
    add_title_block(
        ws,
        "P1-D · Engineering standards",
        "Coverage job + accuracy of CONTRIBUTING / SECURITY against actual code.",
    )
    headers = ["#", "Scenario", "Verification", "Expected",
               "Severity", "Type", "Status", "Notes"]
    rows = [
        [1, "Coverage job exists in ci.yml",
         "grep -A 3 'name: Coverage' .github/workflows/ci.yml",
         "Job present, marked continue-on-error: true, depends on clippy + check.",
         "P2", "Auto", "", ""],
        [2, "Coverage runs locally",
         "cargo install cargo-llvm-cov --locked\n"
         "cargo llvm-cov --workspace --no-default-features --features tui "
         "--exclude momoto-core --exclude momoto-metrics --exclude momoto-intelligence "
         "--lcov --output-path /tmp/lcov.info\n"
         "cargo llvm-cov report --summary-only",
         "Generates lcov.info; summary prints overall %.",
         "P2", "E2E", "", "Operator-time only"],
        [3, "SECURITY.md supported version reflects 0.3.x",
         "grep -A 3 'Supported Versions' SECURITY.md",
         "Table shows 0.3.x supported, < 0.3 unsupported. No more '0.1.x'.",
         "P2", "Auto", "", ""],
        [4, "SECURITY.md describes Network Policy",
         "grep -A 6 'Network Policy' SECURITY.md",
         "Section present, listing loopback / RFC1918 / link-local / IMDS.",
         "P2", "Auto", "", ""],
        [5, "CONTRIBUTING.md clone URL is correct",
         "grep 'git clone' CONTRIBUTING.md",
         "URL is https://github.com/cuervo-ai/halcon.git (NOT halcon-cli.git).",
         "P3", "Auto", "", ""],
        [6, "CONTRIBUTING.md build recipe matches CI",
         "grep '\\-\\-no-default-features' CONTRIBUTING.md",
         "Recipe uses --no-default-features --features tui.",
         "P3", "E2E", "",
         "Operator: copy-paste recipe on a fresh checkout, ensure cargo build succeeds."],
    ]
    write_table(ws, headers, rows, "P1D_Standards", start_row=4)
    autosize(ws, [4, 38, 70, 50, 10, 8, 10, 30])


def sheet_p1e_observability(ws):
    add_title_block(
        ws,
        "P1-E · Observability — NetworkPolicyDenied event variant",
        "Variant is exposed; CLI sink renders it; tracing emits structured logs.",
    )
    headers = ["#", "Scenario", "Verification", "Expected",
               "Severity", "Type", "Status", "Notes"]
    rows = [
        [1, "ToolBlockReason::NetworkPolicyDenied is exported",
         "grep -n 'NetworkPolicyDenied' crates/halcon-runtime-events/src/event.rs",
         "Variant present in enum.",
         "P1", "Auto", "", ""],
        [2, "CLI sink renders the new variant",
         "grep -A 1 'NetworkPolicyDenied' crates/halcon-runtime-events/src/sinks/cli.rs",
         "match arm produces 'network policy denied' string.",
         "P1", "Auto", "", ""],
        [3, "tracing::warn! fires when SSRF blocks a URL (unit-test level)",
         "RUST_LOG=warn cargo test -p halcon-tools network_policy::tests::aws_imds_v4_rejected -- --nocapture",
         "Test passes (warn! is captured by tracing-test once configured).",
         "P2", "Auto", "", ""],
        [4, "End-to-end: agent receives blocked tool result",
         "Operator: instruct halcon to GET http://169.254.169.254/. Inspect the agent's "
         "transcript and any structured log.",
         "Tool output reports network-policy block; if structured logging is enabled "
         "the warn! line is visible with reason=address 169.254.169.254 is blocked.",
         "P1", "E2E", "",
         "Bus emission via runtime_events.rs orphan is Phase 2 work; warn! is the Phase 1 channel."],
    ]
    write_table(ws, headers, rows, "P1E_Observability", start_row=4)
    autosize(ws, [4, 50, 70, 50, 10, 8, 10, 35])


def sheet_smoke(ws):
    add_title_block(
        ws,
        "Build & install smoke tests",
        "Operator runs these on the local machine after pulling the branch.",
    )
    headers = ["#", "Step", "Command", "Expected",
               "Severity", "Type", "Status", "Notes"]
    rows = [
        [1, "Pull the phase-1 branch",
         "git fetch origin phase-1/security-cleanup-ci\n"
         "git checkout phase-1/security-cleanup-ci\n"
         "git log --oneline main..HEAD",
         "Shows 9 commits authored as part of phase 1.",
         "P0", "E2E", "", ""],
        [2, "Format & lint clean",
         "cargo fmt --all -- --check\n"
         "cargo clippy --workspace --no-default-features --features tui "
         "--exclude momoto-core --exclude momoto-metrics --exclude momoto-intelligence -- -D warnings",
         "fmt exits 0; clippy: only pre-existing warnings outside the phase-1 diff.",
         "P0", "E2E", "",
         "If clippy fails on a NEW lint introduced by the diff — gate the PR until fixed."],
        [3, "Workspace tests pass",
         "cargo test --workspace --no-default-features --features tui "
         "--exclude momoto-core --exclude momoto-metrics --exclude momoto-intelligence",
         "Same baseline as main: 6 pre-existing test failures continue (compaction + theme); "
         "no NEW failures from phase-1 work.",
         "P0", "E2E", "", "Compare counts before/after"],
        [4, "Phase-1 unit tests all green",
         "cargo test -p halcon-tools network_policy\n"
         "cargo test -p halcon-auth oauth\n"
         "cargo test -p halcon-providers --features paloma --lib cenzontle::tests::sanitize",
         "17 + 9 + 6 = 32 tests pass.",
         "P0", "E2E", "", ""],
        [5, "Release binary builds",
         "cargo build --release -p halcon-cli --no-default-features --features tui",
         "target/release/halcon present, executable.",
         "P0", "E2E", "", ""],
        [6, "Binary runs (--version, --help)",
         "./target/release/halcon --version\n./target/release/halcon --help",
         "--version prints 0.3.14; --help lists subcommands without panicking.",
         "P0", "E2E", "", ""],
    ]
    write_table(ws, headers, rows, "Smoke", start_row=4)
    autosize(ws, [4, 38, 60, 50, 10, 8, 10, 30])


def sheet_regression(ws):
    add_title_block(
        ws,
        "Cross-cutting regression sweep",
        "Anything we are afraid we might have broken — explicitly checked.",
    )
    headers = ["#", "Risk", "Verification", "Expected",
               "Severity", "Type", "Status", "Notes"]
    rows = [
        [1, "OAuth flows still complete (real Cenzontle)",
         "halcon auth login cenzontle (interactive)",
         "Browser opens; callback handled; token persisted; subsequent /v1/llm/models lists models.",
         "P0", "E2E", "",
         "Most likely real-world break point — OAuth signature changed for OAuthFlow::exchange_code."],
        [2, "MCP servers still connect after subtle dep added",
         "halcon mcp connect (or invoke a tool that uses MCP)",
         "MCP client establishes; PKCE flow completes; tools listed.",
         "P0", "E2E", "", ""],
        [3, "Existing http_request tests still pass with SSRF guard active",
         "cargo test -p halcon-tools http_request",
         "16 tests pass (loopback_blocked_by_network_policy is the new one).",
         "P0", "Auto", "", ""],
        [4, "Existing web_fetch tests still pass with SSRF guard active",
         "cargo test -p halcon-tools web_fetch",
         "15 tests pass; invalid_url_scheme updated to expect ToolOutput-with-error.",
         "P0", "Auto", "", ""],
        [5, "boundary-check still runs clean",
         "bash scripts/check_boundaries.sh",
         "Same warnings as before (no new violations introduced).",
         "P1", "Auto", "", ""],
        [6, "halcon-runtime/executor still compiles and used by serve",
         "cargo check -p halcon-runtime --no-default-features",
         "OK. Removing role_policy/failure_cascade/scheduling did not break coordinator.rs / mutable_dag.rs.",
         "P0", "Auto", "", ""],
        [7, "halcon-cli release binary still functional after security changes",
         "Operator: launch halcon, run a simple prompt that issues web_fetch on a public URL.",
         "Tool succeeds, returns content; no SSRF guard rejection on legitimate URLs.",
         "P0", "E2E", "",
         "Negative test for the SSRF guard — must NOT block legitimate use."],
    ]
    write_table(ws, headers, rows, "Regression", start_row=4)
    autosize(ws, [4, 38, 60, 60, 10, 8, 10, 30])


def sheet_initial_results(ws):
    add_title_block(
        ws,
        "Initial validation run",
        "Captured by the agent on the first integration pass against this branch. "
        "Operator should re-run before merge as final gate.",
    )
    headers = ["Area", "Check", "Command", "Result", "Status", "Date"]
    rows = [
        ["P1-A", "Composite action file present",
         "ls .github/actions/setup-private-deps/action.yml",
         "File present", "PASS", "2026-04-28"],
        ["P1-A", ".cargo/config.toml has git-fetch-with-cli",
         "grep 'git-fetch-with-cli' .cargo/config.toml",
         "git-fetch-with-cli = true", "PASS", "2026-04-28"],
        ["P1-A", "Coverage job in ci.yml",
         "grep 'name: Coverage' .github/workflows/ci.yml",
         "name: Coverage (informational)", "PASS", "2026-04-28"],
        ["P1-A", "Runbook present",
         "ls docs/development/CI_SECRETS.md", "File present", "PASS", "2026-04-28"],
        ["P1-A", "Workflow on real CI",
         "Push branch + observe job", "Pending — needs PALOMA_HTTPS_TOKEN secret",
         "BLOCKED", "—"],
        ["P1-B", "network_policy unit tests",
         "cargo test -p halcon-tools network_policy",
         "17 passed; 0 failed", "PASS", "2026-04-28"],
        ["P1-B", "http_request integration tests",
         "cargo test -p halcon-tools http_request",
         "16 passed; 0 failed", "PASS", "2026-04-28"],
        ["P1-B", "web_fetch integration tests",
         "cargo test -p halcon-tools web_fetch",
         "15 passed; 0 failed", "PASS", "2026-04-28"],
        ["P1-B", "OAuth tests",
         "cargo test -p halcon-auth oauth",
         "9 passed; 0 failed", "PASS", "2026-04-28"],
        ["P1-B", "subtle dependency declared (3 crates)",
         "grep subtle crates/halcon-{auth,cli,mcp}/Cargo.toml",
         "All three crates declare subtle = \"2\"", "PASS", "2026-04-28"],
        ["P1-B", "Sanitization tests",
         "cargo test -p halcon-providers --features paloma --lib cenzontle::tests::sanitize",
         "6 passed; 0 failed", "PASS", "2026-04-28"],
        ["P1-C", "Zombie modules removed",
         "grep -rn 'role_policy|RolePolicy' crates/",
         "Zero hits", "PASS", "2026-04-28"],
        ["P1-C", "Obsolete docs removed",
         "ls docs/STREAMING_*.md docs/SSE_*.md", "No matches", "PASS", "2026-04-28"],
        ["P1-C", "No dangling refs",
         "grep -rn 'STREAMING_BACKEND_GUIDE|REMOTE_CONTROL_V2' . --include='*.md'",
         "Zero hits", "PASS", "2026-04-28"],
        ["P1-C", "Workspace still compiles",
         "cargo check --workspace --no-default-features --features tui --exclude momoto-*",
         "OK; pre-existing warnings only", "PASS", "2026-04-28"],
        ["P1-D", "SECURITY.md updated to 0.3.x",
         "grep '0.3.x' SECURITY.md", "Match present", "PASS", "2026-04-28"],
        ["P1-D", "CONTRIBUTING.md clone URL fixed",
         "grep 'cuervo-ai/halcon.git' CONTRIBUTING.md",
         "URL is halcon.git (not halcon-cli.git)", "PASS", "2026-04-28"],
        ["P1-E", "ToolBlockReason::NetworkPolicyDenied exported",
         "grep NetworkPolicyDenied crates/halcon-runtime-events/src/event.rs",
         "Variant present", "PASS", "2026-04-28"],
        ["P1-E", "CLI sink renders new variant",
         "grep NetworkPolicyDenied crates/halcon-runtime-events/src/sinks/cli.rs",
         "Renders 'network policy denied'", "PASS", "2026-04-28"],
        ["Smoke", "Workspace cargo check (no-default-features tui)",
         "cargo check --workspace --no-default-features --features tui --exclude momoto-*",
         "Finished dev profile, only pre-existing warnings", "PASS", "2026-04-28"],
        ["Smoke", "cargo fmt --check passes",
         "cargo fmt --all -- --check", "Exit 0", "PASS", "2026-04-28"],
        ["Smoke", "Release binary builds",
         "cargo build --release -p halcon-cli --no-default-features --features tui",
         "29 MB binary at target/release/halcon", "PASS", "2026-04-28"],
        ["Smoke", "halcon --help",
         "./target/release/halcon --help",
         "Subcommands listed (chat/config/init/status/auth …)", "PASS", "2026-04-28"],
        ["Regression", "boundary-check still runs clean",
         "bash scripts/check_boundaries.sh",
         "PASS (0 strict violations; pre-existing /tasks warn)", "PASS", "2026-04-28"],
        ["Regression", "halcon-runtime still compiles after removals",
         "cargo check -p halcon-runtime --no-default-features",
         "OK; coordinator/mutable_dag intact", "PASS", "2026-04-28"],
        ["E2E", "Real-binary SSRF block (interactive)",
         "Operator: prompt halcon to GET 127.0.0.1",
         "Pending operator validation",
         "BLOCKED", "—"],
        ["E2E", "OAuth login happy path (Cenzontle)",
         "halcon auth login cenzontle (real flow)",
         "Pending operator validation", "BLOCKED", "—"],
    ]
    write_table(ws, headers, rows, "InitialResults", start_row=4)
    autosize(ws, [10, 50, 75, 60, 10, 12])


def sheet_decisions(ws):
    add_title_block(
        ws,
        "Phase-2 decision queue",
        "Cross-team decisions that must precede further code changes.",
    )
    headers = ["ID", "Decision", "Stakeholders", "Blocks", "Target date", "Status"]
    rows = [
        ["D-1", "Tordo accepts ExecutionPlanV1 (signed) and verifies HMAC",
         "Tordo Lead, Paloma Lead, Halcón Lead", "Retiring 9 LLM adapters", "+7d", ""],
        ["D-2", "Rust types from cuervo-contracts (codegen path)",
         "cuervo-contracts maintainer, Paloma, Halcón", "Adopting canonical contracts in Rust", "+14d", ""],
        ["D-3", "Activate Urraca (when?) or archive it",
         "Urraca Lead, Halcón Lead", "Long-term memory strategy", "+14d", ""],
        ["D-4", "Halcón delegates end-user auth to cuervo-auth-service /validate",
         "cuervo-auth-service Lead, Halcón Lead", "halcon-auth refactor", "+14d", ""],
        ["D-5", "Externalise prompts to cuervo-prompt-service",
         "prompt-service Lead, Halcón Lead", "halcon-cli/prompts/ retirement", "+30d", ""],
        ["D-6", "Cenzontle exclusive vs multi-provider as default",
         "CTO, architecture", "default_provider in config", "+7d", ""],
        ["D-7", "GDEM (halcon-agent-core) — activate or delete",
         "Agent Lead, CTO", "12k LOC zombie crate", "+3d", ""],
        ["D-8", "halcon-cli/src/repl/runtime_events.rs orphan — resurrect or delete",
         "Halcón Lead", "Runtime events bus emission", "+7d",
         "DISCOVERED in P1-E"],
    ]
    write_table(ws, headers, rows, "Decisions", start_row=4)
    autosize(ws, [6, 60, 30, 35, 12, 30])


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    wb = Workbook()

    # Replace default sheet with our Summary sheet.
    ws = wb.active
    ws.title = "Summary"
    sheet_summary(ws)

    sheet_p1a_ci(wb.create_sheet("P1-A_CI"))
    sheet_p1b_ssrf(wb.create_sheet("P1-B_SSRF"))
    sheet_p1b_oauth(wb.create_sheet("P1-B_OAuth"))
    sheet_p1b_logsanit(wb.create_sheet("P1-B_LogSanit"))
    sheet_p1c_cleanup(wb.create_sheet("P1-C_Cleanup"))
    sheet_p1d_standards(wb.create_sheet("P1-D_Standards"))
    sheet_p1e_observability(wb.create_sheet("P1-E_Observability"))
    sheet_smoke(wb.create_sheet("Smoke"))
    sheet_regression(wb.create_sheet("Regression"))
    sheet_initial_results(wb.create_sheet("Initial Results"))
    sheet_decisions(wb.create_sheet("Phase-2 Decisions"))

    wb.save(OUT)
    print(f"wrote {OUT}")
    print(f"size: {os.path.getsize(OUT)} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
